DROP TABLE IF EXISTS challenges;
CREATE TABLE challenges (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    short_description TEXT NOT NULL
);